language: node_js
node_js: 8
services:
  - docker
script:
  - npm run-script build
  - 'docker build -t ${TRAVIS_REPO_SLUG} .'
  - 'docker build -t dredd-tests . -f ./tests/Dockerfile'
  - 'docker-compose -f ./tests/docker-compose.yml up -d kafka data-broker-redis'
  - 'docker-compose -f ./tests/docker-compose.yml run data-broker'
install:
  - npm install
after_success:
  - travis/publish.sh
  