sudo: false
language: node_js
node_js: 8
script:
  - npm run-script build
  - docker build -t ${TRAVIS_REPO_SLUG} . -f ./docker/Dockerfile
  - docker build -t dredd-data-broker . -f ./tests/Dockerfile
  - cd tests
  - docker-compose run data-broker
before_script:
  - cd tests
  - docker-compose up -d kafka data-broker-redis
  - cd ..
install:
  - npm install
after_success:
  - travis/publish.sh